#production: &production
#  host: <%= ENV.fetch("REDIS_SHARED_HOST", "127.0.0.1") %>
#  port: <%= ENV.fetch("REDIS_SHARED_PORT", "6379") %>
#  password: "gh-revue"
#  timeout: 1
#
#development: &development
#  host: <%= ENV.fetch("REDIS_SHARED_HOST", "127.0.0.1") %>
#  port: <%= ENV.fetch("REDIS_SHARED_PORT", "6379") %>
#  password: "gh-revue"
#  timeout: 1

#
production: &production
  url: <%= ENV.fetch("REDIS_HOST", "redis://127.0.0.1:6379/0") %>
  password: <%= ENV.fetch("REDIS_PASSWORD", "gh-revue") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("REDIS_HOST", "redis://127.0.0.1:6379/0") %>
  password: <%= ENV.fetch("REDIS_PASSWORD", "gh-revue") %>
  timeout: 1

test:
  <<: *development
