name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      RAILS_ENV: test
      REDIS_PASSWORD: ""
    services:
      redis:
        image: redis:6.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Ruby Dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Rspec
      run: |
        bundle exec rspec
    - name: Brakeman
      run: |
        bundle exec brakeman
    - name: Standard
      run: |
        bundle exec standardrb
    - name: Dump GitHub context
      run: echo ${{ toJson(github) }}
    - name: Code Climate Code Coverage
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: paambaati/codeclimate-action@v2.7.5
