name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.0
    env:
      RAILS_ENV: test
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
    services:
      redis:
        image: redis:6.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Nodejs LTS
      run: |
        apt-get -y update && apt-get -y upgrade && apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs
    - name: Install Yarn
      run: |
        npm install -g yarn
    - name: Install Ruby Dependencies
      run: |
        gem install bundler
        bundle install
    - name: Rspec
      run: |
        bundle exec rspec spec
    - name: Brakeman
      run: |
        brakeman
    - name: Standard
      run: |
        bundle exec standardrb
    - name: Code Climate Code Coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: bundle exec rspec --format progress
